# syntax=docker/dockerfile:1

## Build

FROM golang:1.18 AS build

WORKDIR /todo-app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY ./ ./

RUN go build -o ./bin/main cmd/*.go

## Deploy

FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY --from=build /todo-app/ ./

EXPOSE 8000

CMD ["./bin/main"]
